### ISSUE TITLE
Possible mistake

### ISSUE THREAD

**Issue by miaza0** [ThibaultJanBeyer/cheatsheets#1]
Correct me if Im wrong, but in rails 

@variable = instance variable name
@@variable = class variable name

if so, you may have a mistake in your cheatsheet in the section where you explain classes for ruby

**Comment by ThibaultJanBeyer** [comment]
Hey miaza0, thanks for your interest in the cheatsheets! I think you are right. Would you be so kind to create a Pull Request directly? Thank you
